language: python

install:
  # https://github.com/wummel/linkchecker/issues/649
  # https://github.com/linkchecker/linkchecker/pull/40
  #- pip install requests==2.9.1
  #- pip install LinkChecker==9.3
  - pip install pelican markdown BeautifulSoup4

  # grab the theme
  - git clone https://github.com/maggick/maggner-pelican

  # grab the pelican plugins
  - git clone --recursive https://github.com/getpelican/pelican-plugins

  # grab the latest published version in order to not erase rss feed
  - git clone https://github.com/maggick/maggick.github.io output

script:
  #- linkchecker ./content
  - pelican -D

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && cd output && git add ./ && git -c user.name="Travis CI for maggick" -c user.email="keller.mdp@gmail.com" commit -m 'Travis update' && git push https://${GH_TOKEN}@github.com/maggick/maggick.github.io.git master
